username: jestesbitch
password: ~
hostname: example.com
servername: example.com
realname: n/a
server:   chat.freenode.net
port:     6667
debug:    true

trusted:
    - f1gm3nt

###
# Put the class here
plugins:
    # @see src/Phillip/CorePlugin.php
    - 'Phillip\CorePlugin'
